apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-blue
  labels:
    app: demo-app
    version: blue
spec:
  replicas: 3



  selector:
    matchLabels:
      app: demo-app
      version: blue

  template:
    metadata:
      labels:
        app: demo-app
        version: blue

    spec:
      containers:
        - name: demo-app
          image: yaqublurufat/demo-app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8088

          resources:
            requests:
              memory: "216Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

