spring.application.name=Spring Rest API
server.port=8087

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=messigoat10
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
JWT_SECRET=3ISVpTxIMX4DmQUCWxBacSwV7iYBS96QcGp9/Zkb9/k=
jwt.expiration=86400000

springdoc.enable-hateoas=false
springdoc.enable-data-rest=false


