spring.application.name=ord-service
server.port=8093
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=messigoat10
spring.jpa.properties.hibernate.default_schema=students
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

market-service.url=http://localhost:8091
product-service.url=http://localhost:8092
JWT_SECRET=3ISVpTxIMX4DmQUCWxBacSwV7iYBS96QcGp9/Zkb9/k=
