name: CI-CD Pipeline

on:
  push:
    branches: ["rufat"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t yaqublurufat/demo-app:v${{ github.run_number }} .

      - name: Push Docker image
        run: |
          docker push yaqublurufat/demo-app:v${{ github.run_number }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Test cluster connection
        run: |
          kubectl config current-context
          kubectl get nodes

      - name: Deploy new image
        run: |
          kubectl set image deployment/demo-app \
          demo-app=yaqublurufat/demo-app:v${{ github.run_number }}

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/demo-app